---
- name: Create ec2 security group
  ec2_group:
    name: "{{ sg_name }}"
    description: "{{ project }} security group"
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: all
        cidr_ip: "{{ vpc_cidr_block }}"
  register: vpc_sg
  tags:
    - provision
